smokey_pork_sliders:
  id: 1
  user_id: 1
  calories: 1000
  cook_time: <%= 1.hour.to_i %>
  description: 'These mini burgers are absolutely stunning, all smoky from the bacon and paprika and with the sweet and sour hit from the homemade barbeque sauce. People often add too much to their burgers thinking it will enrich the flavor, but let me tell you, when it comes to burgers, less is more. Trust me.'
  number_of_servings: 4
  prep_time: <%= 30.minutes.to_i %>
  recipe_category: 'bbq'
  total_time: <%= (1.hour + 30.minutes).to_i %>
  title: 'Smokey Pork Sliders with Barbecue Sauce'
  images:
    - filepath: 'db/images/smokey_pork_sliders.jpg'
      filename: 'smokey_pork_sliders.jpg'
  labels:
    - pork
    - dinner
    - entertaining
  ingredient_groups:
    - ingredients:
        - number: 4
          name: 'strips of rindless smoked bacon, finely chopped'
        - name: 'Olive oil'
        - number: 1
          name: 'shallot, peeled and finely chopped'
        - number: 1
          name: 'smoked paprika'
          unit_of_measurement: 'tsp'
        - number: 1
          name: 'ground pork'
          unit_of_measurement: 'pound'
        - name: 'sea salt'
        - name: 'freshly ground black pepper'
    - name: 'For the barbecue sauce'
      ingredients:
        - name: 'Olive oil'
        - number: 1
          name: 'small onion, peeled and finely diced'
        - number: 2
          name: 'garlic cloves, finely chopped'
        - name: 'Sea salt and freshly ground black pepper'
        - number: 1
          name: 'brown sugar'
          unit_of_measurement: 'Tbsp'
        - number: 1
          name: 'smoked paprika'
          unit_of_measurement: 'tsp'
        - number: 1
          name: 'cider vinegar'
          unit_of_measurement: 'Tbsp'
        - number: 2
          name: 'Worcestershire sauce'
          unit_of_measurement: 'tsp'
        - number: 6
          name: 'tomato ketchup'
          unit_of_measurement: 'Tbsp'
    - name: 'To serve'
      ingredients:
        - name: 'Mini burger buns/bread rolls'
          ingredient_group: to_serve
        - name: 'Baby Boston lettuce leaves, shredded'
          ingredient_group: to_serve
        - name: 'Slices of smoked Cheddar cheese'
          ingredient_group: to_serve
        - name: 'Slices of tomato'
          ingredient_group: to_serve
  instructions:
    - 'First make the barbeque sauce. Heat the oil in a frying pan, add the onion and garlic with some salt and pepper and the sugar, and cook for 5 minutes until softened. Add the paprika and stir to combine. Cook for 10-15 minutes until the onion is caramelizing, then add the vinegar and let it cook for a coupole of minuts. Add the Worcestershire sauce and tomato ketchup, mix well, and continue to cook for about 8 minutes until the sauce has reduced to a dropping consistency. Taste and adjust the seasoning as necessary. Remove from the heat and set aside.'
    - 'While the barbecue sauce is reducing, start preparing the burgers. Cook the bacon in an oiled pan for about 5 minutes until almost cooked through. Add the shallot and continue to cook for 5 minutes untul the shallot is tender and the bacon is crisp. Sprinkle in the smoked paprika and mix well. Continue to cook for 1-2 minuts, then remove from the heat, draining off any excess fat on paper towels, and cool.'
    - 'Season the ground pork with salt and pepper and mix well with the cooked shallots and bacon. Shape into balls the size of golf balls and flatten into patties.'
    - 'Heat a large, heavy-bottomed frying pan with a little oil. Season the patties and cook them for 1-2 minutes on each side, basting with the juices until cooked through and colored. Turn off the heat and leave them to rest in the pan. Top each patty with a slice of cheese, allowing it to melt slightly.'
    - 'Assemble your sliders in mini buns, layered with the barbecue sauce, lettuce, and slices of tomato. Any remaining barbecue sauce will keep in the fridge very well. Serve immediately.'
peri_peri_chicken:
  id: 2
  user_id: 1
  calories: 1000
  cook_time: <%= (1.hour + 20.minutes).to_i %>
  description: "This is a replica of Nando's peri peri chicken recipe."
  number_of_servings: 6
  prep_time: <%= 5.minutes %>
  recipe_category: 'bbq'
  total_time: <%= (1.hour + 25.minutes).to_i %>
  title: 'Portugese BBQ Peri Peri Chicken'
  labels:
    - chicken
    - dinner
  images:
    - filepath: 'db/images/portugese_bbq_peri_peri_chicken.jpg'
      filename: 'portugese_bbq_peri_peri_chicken.jpg'
  ingredient_groups:
    - ingredients:
        - number: 1.5
          unit_of_measurement: 'kg'
          name: whole chicken (Butterflied is preferred)
        - name: Salt and pepper to season
    - name: 'For the marinade'
      ingredients:
        - number: '1/2'
          ingredient_group: marinade
          unit_of_measurement: 'cup'
          name: 'vegetable oil'
        - number: '1/3 '
          ingredient_group: marinade
          unit_of_measurement: 'cup'
          name: 'BBQ sauce'
        - number: 3
          ingredient_group: marinade
          unit_of_measurement: 'Tbsp'
          name: 'Worcestershire sauce'
        - number: 2
          ingredient_group: marinade
          unit_of_measurement: 'Tbsp'
          name: 'minced garlic'
        - number: 1
          ingredient_group: marinade
          unit_of_measurement: 'Tbsp'
          name: 'onion powder'
        - number: 2
          ingredient_group: marinade
          unit_of_measurement: 'tsp'
          name: 'fresh squeezed lemon juice (optional)'
        - number: 3
          ingredient_group: marinade
          unit_of_measurement: 'tsp'
          name: 'sriracha'
        - number: 1
          ingredient_group: marinade
          unit_of_measurement: 'tsp'
          name: 'yellow mustard'
        - number: 2
          ingredient_group: marinade
          unit_of_measurement: 'tsp'
          name: salt
        - name: 'Cracked black pepper, to taste (optional)'
          ingredient_group: marinade
  instructions:
    - "Mix all of the marinade ingredients (except for the Sriracha) together until well combined. Mix in 2-4 tsp of Sriracha, taste test, and work up from there until reaching your desired level of heat (or leave it out all together if you don't want any spice at all)."
    - "Using 3/4 of the marinade, coat the chicken evenly on the outside, as well as under the skin where possible (the breast especially), until fully coated in sauce. Cover with plastic wrap and refrigerate over night if time allows. (I recommend a minimum marinade time of two hours for this chicken. The longer you leave it, the better the flavours."
    - "When ready to cook, arrange oven shelf to the middle of the oven, and preheat to 470°F | 245°C."
    - "Remove the chicken from the refrigerator and let it sit on a bench top for 20 minutes, or just enough time to take the chill out of the chicken. (I find 20 minutes plenty of time. Don't leave it any longer than half an hour at room temperature.)"
    - "Heat 2 Tbsp of oil in an oven proof pan or well seasoned skillet over medium heat. When pan is hot, place the chicken, breast-side down into the pan, and sear for a good 5-6 minutes, until the skin becomes golden browned. Flip and sear on the other side for a further 5 minutes."
    - "Add 2 more Tbsp of vegetable oil to the remaining marinade, and pour half of it over the chicken. Use a basting brush to coat evenly."
    - "Place the chicken in the preheated oven, and cook for 55-60 minutes, or until cooked right through to the centre and juices run clear."
    - "Once the chicken is done, baste with the pan drippings and serve with any remaining UNTOUCHED marinade to use as a dipping sauce."